import assert from 'node:assert/strict';
const root='http://localhost:5173';
const adminPassword=process.env.TEST_ADMIN_PASSWORD,staffPassword=process.env.TEST_STAFF_PASSWORD;
assert.ok(adminPassword&&staffPassword,'Set TEST_ADMIN_PASSWORD and TEST_STAFF_PASSWORD for the local test');
async function req(path,body,cookie='',origin=root){const r=await fetch(root+path,{method:body?'POST':'GET',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json().catch(()=>({})),cookie:r.headers.get('set-cookie')?.split(';')[0]||'',headers:r.headers};}
const login=(username,password)=>req('/api/auth',{action:'login',username,password});
assert.equal((await req('/api/pos')).status,401);
assert.equal((await req('/api/users')).status,403);
assert.equal((await login('Admin1','wrong-test-value')).status,401);
const admin=await login('Admin1',adminPassword);assert.equal(admin.status,200);assert.equal(admin.data.role,'admin');
assert.ok(admin.headers.get('set-cookie').includes('HttpOnly'));assert.ok(admin.headers.get('set-cookie').includes('SameSite=Strict'));
const staff=await login('P01',staffPassword);assert.equal(staff.status,200);assert.equal(staff.data.role,'staff');
const call=(body,cookie=admin.cookie)=>req('/api/pos',body,cookie);
assert.equal((await req('/api/pos',{action:'seed'},admin.cookie,'https://invalid.example')).status,403);
const p={id:crypto.randomUUID(),name:'AUTH TEST ONLY',price:3500,category:'ทดสอบ',active:1};
assert.equal((await call({action:'product',product:p},staff.cookie)).status,403);
assert.equal((await call({action:'seed'},staff.cookie)).status,403);
assert.equal((await req('/api/users',undefined,staff.cookie)).status,403);
assert.equal((await req('/api/users',{action:'create',username:'blocked',password:'blocked'},staff.cookie)).status,403);
assert.equal((await call({action:'product',product:p})).status,200);
assert.ok((await call(undefined,staff.cookie)).data.products.some(x=>x.id===p.id));
const sale={id:crypto.randomUUID(),method:'cash',received:10000,items:[{productId:p.id,price:3500,qty:2,note:'เส้นเล็ก'}]};
assert.equal((await call({action:'sale',sale:{...sale,received:6000}},staff.cookie)).status,400);
assert.equal((await call({action:'sale',sale:{...sale,items:[{...sale.items[0],qty:-1}]}},staff.cookie)).status,400);
assert.equal((await call({action:'sale',sale:{...sale,items:[{...sale.items[0],price:1}]}},staff.cookie)).status,409);
const duplicate=await Promise.all([call({action:'sale',sale},staff.cookie),call({action:'sale',sale},staff.cookie)]);assert.ok(duplicate.every(r=>r.status===200));
let state=(await call()).data;assert.equal(state.orders.filter(o=>o.id===sale.id).length,1);const order=state.orders.find(o=>o.id===sale.id);assert.equal(order.total,7000);assert.equal(order.received-order.total,3000);
await call({action:'product',product:{...p,price:4500}});assert.equal((await call()).data.orders.find(o=>o.id===sale.id).items[0].price,3500);
assert.equal((await call({action:'cancel',id:sale.id,reason:''},staff.cookie)).status,400);
assert.equal((await call({action:'cancel',id:sale.id,reason:'ทดสอบพนักงานยกเลิก'},staff.cookie)).status,200);
assert.ok((await call()).data.orders.find(o=>o.id===sale.id).cancelled);
const transfer={...sale,id:crypto.randomUUID(),method:'transfer',received:0,items:[{...sale.items[0],price:4500,qty:1}]};assert.equal((await call({action:'sale',sale:transfer},staff.cookie)).status,200);assert.equal((await call()).data.orders.find(o=>o.id===transfer.id).received,4500);
await call({action:'cancel',id:transfer.id,reason:'สิ้นสุดทดสอบ'},staff.cookie);await call({action:'product',product:{...p,active:0}});
const username='test_'+crypto.randomUUID().slice(0,8),password=crypto.randomUUID();
assert.equal((await req('/api/users',{action:'create',username,password},admin.cookie)).status,200);
const created=(await req('/api/users',undefined,admin.cookie)).data.users.find(u=>u.username===username);assert.ok(created);assert.equal(created.password_hash,undefined);
const newLogin=await login(username,password);assert.equal(newLogin.status,200);
assert.equal((await req('/api/users',{action:'disable',id:created.id},admin.cookie)).status,200);assert.equal((await req('/api/pos',undefined,newLogin.cookie)).status,401);
assert.equal((await login(username,password)).status,401);
assert.equal((await req('/api/auth',{action:'logout'},staff.cookie)).status,200);assert.equal((await call(undefined,staff.cookie)).status,401);
assert.equal((await req('/api/pos',undefined,staff.cookie+'forged')).status,401);
const invalid='invalid_'+crypto.randomUUID().slice(0,8);for(let i=0;i<5;i++)assert.equal((await login(invalid,'bad')).status,401);assert.equal((await login(invalid,'bad')).status,429);
console.log('PASS: admin/staff login, HttpOnly cookies, role checks, shared shop data, cash/transfer, duplicate submit, immutable old prices, staff cancellation, account creation/disabling, revoked and forged sessions, and login rate limits. Local-only test records retained and cancelled.');
