'use client';
import {useEffect,useRef,useState} from 'react';
import SheetsExport from './sheets-export';
import StaffAccounts from './staff-accounts';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ShoppingBasket,ReceiptText,ChartNoAxesCombined,Utensils,Plus,Minus,Check,ArrowUpRight,Download,RefreshCw} from 'lucide-react';
import {money,dayKey,satang,noodles,type Product,type Line,type Order} from '@/lib/pos';

async function api(body?:unknown){const res=await fetch('/api/pos',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await res.json() as {error?:string; products:Product[]; orders:Order[]};if(!res.ok)throw Object.assign(new Error(data.error||'เชื่อมต่อไม่ได้'),{status:res.status});return data;}
const clock=(date:string)=>new Date(date).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'});
const shortId=(id:string)=>id.replaceAll('-','').slice(0,8).toUpperCase();
export default function Pos({userKey,role,username}:{userKey:string;role:'admin'|'staff';username:string}){
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[cart,setCart]=useState<Line[]>([]),[tab,setTab]=useState('sell'),[category,setCategory]=useState('ทั้งหมด'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [selected,setSelected]=useState<Product|null>(null),[noodle,setNoodle]=useState(noodles[1]),[note,setNote]=useState(''),[checkout,setCheckout]=useState(false),[method,setMethod]=useState<'cash'|'transfer'>('cash'),[received,setReceived]=useState(''),[editing,setEditing]=useState<Product|null>(null),[detail,setDetail]=useState<Order|null>(null),[reason,setReason]=useState(''),[date,setDate]=useState(dayKey()),[search,setSearch]=useState('');
 const locked=useRef(false),requestId=useRef(''),pendingSale=useRef<unknown>(null);
 const [draftReady,setDraftReady]=useState(false);
 const storageKey=`noodle-draft-${userKey}`;
 useEffect(()=>{try{const raw=sessionStorage.getItem(storageKey);if(raw){const draft=JSON.parse(raw);if(Array.isArray(draft.cart))setCart(draft.cart);if(draft.pendingSale){pendingSale.current=draft.pendingSale;requestId.current=draft.pendingSale.id;setMethod(draft.pendingSale.method);setReceived(String(draft.pendingSale.received/100));setCheckout(true);}}}catch{}setDraftReady(true);},[storageKey]);
 useEffect(()=>{if(draftReady){try{sessionStorage.setItem(storageKey,JSON.stringify({cart,pendingSale:pendingSale.current}));}catch{}}},[cart,busy,draftReady,storageKey]);
 const total=cart.reduce((n,l)=>n+l.price*l.qty,0),count=cart.reduce((n,l)=>n+l.qty,0);
 const daily=orders.filter(o=>dayKey(new Date(o.created))===date),paid=daily.filter(o=>!o.cancelled),revenue=paid.reduce((n,o)=>n+o.total,0);
 async function reload(){const data=await api();setProducts(data.products);setOrders(data.orders);}
 useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function act(fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'เกิดข้อผิดพลาด');}finally{locked.current=false;setBusy(false);}}
 function add(){if(!selected)return;const notes=[selected.category==='เกาเหลา'?'':noodle,note.trim()].filter(Boolean).join(' · ');setCart(old=>{const existing=old.findIndex(l=>l.productId===selected.id&&l.note===notes);if(existing<0)return [...old,{productId:selected.id,name:selected.name,price:selected.price,qty:1,note:notes}];return old.map((l,i)=>i===existing?{...l,qty:Math.min(999,l.qty+1)}:l);});setSelected(null);setNote('');setMessage('');}
 function changeQty(index:number,diff:number){setCart(old=>old.map((l,i)=>i===index?{...l,qty:Math.min(999,l.qty+diff)}:l).filter(l=>l.qty>0));}
 function startCheckout(){requestId.current=crypto.randomUUID();pendingSale.current=null;setReceived('');setMethod('cash');setCheckout(true);setError('');}
 async function pay(){await act(async()=>{const cash=method==='cash'?satang(received):total;if(cash<total)throw new Error('เงินที่รับยังไม่ครบยอด');if(!pendingSale.current)pendingSale.current={id:requestId.current,method,received:cash,items:cart.map(({productId,price,qty,note})=>({productId,price,qty,note}))};try{sessionStorage.setItem(storageKey,JSON.stringify({cart,pendingSale:pendingSale.current}));}catch{}try{await api({action:'sale',sale:pendingSale.current});}catch(e){if(e instanceof Error&&'status' in e&&(e.status===400||e.status===409)){pendingSale.current=null;}throw e;}setMessage(`บันทึกบิลแล้ว${method==='cash'?` · เงินทอน ${money(cash-total)}`:''}`);setCart([]);setCheckout(false);pendingSale.current=null;await reload();});}
 function exportData(){const blob=new Blob([JSON.stringify({version:1,shop:'ก๋วยเตี๋ยวไก่มะระ',exportedAt:new Date().toISOString(),products,orders},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`noodle-pos-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const controller=new AbortController();try{context.registerTool({name:'read_pos_menu',description:'Read available menu items and prices in satang. Does not place an order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');const data=await api();return {products:data.products};}},{signal:controller.signal});}catch{}return()=>controller.abort();},[]);
 const categories=['ทั้งหมด',...Array.from(new Set(products.filter(p=>p.active).map(p=>p.category)))];
 return <div className="pos-app"><header className="topbar"><div className="brand-mark">ไก่</div><div><h1>ก๋วยเตี๋ยวไก่มะระ</h1><p>{username} · {role==='admin'?'แอดมิน':'พนักงาน'}</p></div><Button variant="ghost" size="icon" aria-label="โหลดข้อมูลใหม่" disabled={busy} onClick={()=>act(reload)}><RefreshCw/></Button><Button variant="outline" disabled={busy} onClick={()=>act(async()=>{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!r.ok)throw new Error('ออกจากระบบไม่ได้ กรุณาลองใหม่');sessionStorage.removeItem(storageKey);window.location.assign('/');})}>ออก</Button></header>
 <Tabs value={tab} onValueChange={setTab} className="app-tabs"><TabsList className="main-nav"><TabsTrigger value="sell"><ShoppingBasket/>ขาย</TabsTrigger><TabsTrigger value="history"><ReceiptText/>บิล</TabsTrigger><TabsTrigger value="report"><ChartNoAxesCombined/>ยอดขาย</TabsTrigger>{role==='admin'&&<TabsTrigger value="menu"><Utensils/>จัดการ</TabsTrigger>}</TabsList>
 <main>{error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success" role="status"><Check/>{message}</div>}{loading?<div className="empty">กำลังโหลดเมนูและบิล…</div>:<>
 <TabsContent value="sell"><div className="section-heading"><div><span className="eyebrow">รับออเดอร์</span><h2>วันนี้ทานอะไรดี?</h2></div><span className="small-muted">{new Date().toLocaleDateString('th-TH',{day:'numeric',month:'short',timeZone:'Asia/Bangkok'})}</span></div>
 {!products.length?<div className="empty"><Utensils/><h3>เตรียมเมนู เปิดร้านได้เลย</h3><p>เมนูตามภาพของร้าน ธรรมดา 35 / พิเศษ 45 / เกาเหลา 50 บาท</p><Button disabled={busy} onClick={()=>act(async()=>{await api({action:'seed'});await reload();})}>เพิ่มเมนูของร้าน</Button></div>:<><div className="category-row">{categories.map(c=><Button key={c} variant={category===c?'default':'outline'} onClick={()=>setCategory(c)}>{c}</Button>)}</div><div className="selling-layout"><div className="menu-grid">{products.filter(p=>p.active&&(category==='ทั้งหมด'||p.category===category)).map(p=><Button variant="outline" className="menu-card" key={p.id} onClick={()=>{setSelected(p);setNote('');}}><span className="menu-category">{p.category}</span><strong>{p.name.replace(' ธรรมดา','').replace(' พิเศษ','')}</strong><span className="menu-size">{p.name.endsWith('พิเศษ')?'พิเศษ':p.name.endsWith('ธรรมดา')?'ธรรมดา':'ไม่ใส่เส้น'}</span><span className="menu-bottom"><b>{money(p.price)}</b><Plus aria-hidden="true"/></span></Button>)}</div>
 <section className="cart-panel"><div className="cart-title"><h3>บิลนี้</h3><span>{count} รายการ</span></div>{cart.length===0?<p className="cart-empty">เลือกเมนูเพื่อเริ่มบิลใหม่</p>:cart.map((line,i)=><div className="cart-line" key={`${line.productId}-${line.note}`}><div><strong>{line.name}</strong><p>{line.note}</p><b>{money(line.price*line.qty)}</b></div><div className="quantity"><Button variant="outline" size="icon" aria-label={`ลดจำนวน ${line.name}`} onClick={()=>changeQty(i,-1)}><Minus/></Button><span>{line.qty}</span><Button variant="outline" size="icon" aria-label={`เพิ่มจำนวน ${line.name}`} onClick={()=>changeQty(i,1)}><Plus/></Button></div></div>)}<div className="cart-total"><span>รวมทั้งหมด</span><strong>{money(total)}</strong></div><Button className="pay-button" disabled={!cart.length||busy} onClick={startCheckout}>รับชำระเงิน <ArrowUpRight/></Button></section></div></>}
 </TabsContent>
 <TabsContent value="history"><div className="section-heading"><div><span className="eyebrow">รายการขาย</span><h2>ประวัติบิล</h2></div><Label className="date-filter">วันที่<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Label></div><Input placeholder="ค้นหาเลขบิล หรือชื่อเมนู" aria-label="ค้นหาบิล" value={search} onChange={e=>setSearch(e.target.value)}/><div className="history-list">{daily.filter(o=>shortId(o.id).toLowerCase().includes(search.toLowerCase())||o.items.some(l=>l.name.includes(search))).map(o=><Button variant="outline" className="bill-card" key={o.id} onClick={()=>{setDetail(o);setReason('');}}><div><strong>#{shortId(o.id)}</strong><span>{clock(o.created)} · {o.method==='cash'?'เงินสด':'เงินโอน'}</span></div><div><b>{money(o.total)}</b><span className={o.cancelled?'cancelled':'paid'}>{o.cancelled?'ยกเลิกแล้ว':'จ่ายแล้ว'}</span></div></Button>)}</div>{!daily.length&&<div className="empty">ยังไม่มีบิลในวันที่เลือก</div>}</TabsContent>
 <TabsContent value="report"><div className="section-heading"><div><span className="eyebrow">ภาพรวมของร้าน</span><h2>สรุปยอดขาย</h2></div><Label className="date-filter">วันที่<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Label></div><section className="revenue"><span>ยอดขายสุทธิ</span><strong>{money(revenue)}</strong><p>{paid.length} บิลที่ชำระแล้ว · ยกเลิก {daily.length-paid.length} บิล</p></section><div className="stats-grid">{(['cash','transfer'] as const).map(m=><div key={m}><span>{m==='cash'?'เงินสด':'เงินโอน'}</span><strong>{money(paid.filter(o=>o.method===m).reduce((n,o)=>n+o.total,0))}</strong></div>)}</div><section className="report-section"><h3>เมนูขายดี</h3>{Object.entries(paid.flatMap(o=>o.items).reduce<Record<string,number>>((m,l)=>({...m,[l.name]:(m[l.name]||0)+l.qty}),{})).sort((a,b)=>b[1]-a[1]).map(([name,qty],i)=><div className="ranking" key={name}><span>{i+1}</span><strong>{name}</strong><b>{qty} ชาม</b></div>)}{!paid.length&&<p className="small-muted">ยังไม่มีรายการขายในวันที่เลือก</p>}</section>{role==='admin'&&<SheetsExport date={date}/>}<Button variant="outline" onClick={exportData}><Download/>ส่งออกข้อมูลทั้งหมด (JSON)</Button><p className="small-muted backup-note">ไฟล์ประกอบด้วยเมนูและบิลทั้งหมด เก็บไว้สำรองหรือนำไปวิเคราะห์ต่อ</p></TabsContent>
 {role==='admin'&&<TabsContent value="menu"><div className="section-heading"><div><span className="eyebrow">ตั้งค่าร้าน</span><h2>จัดการเมนู</h2></div><Button onClick={()=>setEditing({id:crypto.randomUUID(),name:'',price:3500,category:'ก๋วยเตี๋ยวไก่',active:1})}><Plus/>เพิ่มเมนู</Button></div><p className="small-muted">ราคาใหม่มีผลกับบิลใหม่ บิลที่ขายแล้วจะเก็บราคาเดิม</p><div className="history-list">{products.map(p=><Button variant="outline" className="bill-card" key={p.id} onClick={()=>setEditing({...p})}><div><strong>{p.name}</strong><span>{p.category} · {p.active?'เปิดขาย':'ปิดขาย'}</span></div><b>{money(p.price)}</b></Button>)}</div><StaffAccounts/></TabsContent>}</> }</main></Tabs>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?money(selected.price):''} ต่อชาม</DialogDescription></DialogHeader>{selected?.category!=='เกาเหลา'&&<><Label>เลือกเส้น</Label><div className="noodle-grid">{noodles.map(n=><Button variant={noodle===n?'default':'outline'} key={n} onClick={()=>setNoodle(n)}>{n}</Button>)}</div></>}<Label htmlFor="note">เพิ่มเติม เช่น ไม่ผัก ไม่เผ็ด</Label><Input id="note" value={note} maxLength={120} onChange={e=>setNote(e.target.value)}/><Button onClick={add}>เพิ่มลงบิล</Button></DialogContent></Dialog>
 <Dialog open={checkout} onOpenChange={v=>{if(!busy&&!pendingSale.current)setCheckout(v);}}><DialogContent showCloseButton={!busy&&!pendingSale.current}><DialogHeader><DialogTitle>รับชำระเงิน</DialogTitle><DialogDescription>{count} รายการ · ยืนยันหลังรับเงินจากลูกค้าแล้ว</DialogDescription></DialogHeader><strong className="checkout-total">{money(total)}</strong><div className="payment-methods"><Button disabled={busy||!!pendingSale.current} variant={method==='cash'?'default':'outline'} onClick={()=>setMethod('cash')}>เงินสด</Button><Button disabled={busy||!!pendingSale.current} variant={method==='transfer'?'default':'outline'} onClick={()=>setMethod('transfer')}>เงินโอน</Button></div>{method==='cash'?<><Label htmlFor="received">รับเงินมา (บาท)</Label><Input id="received" inputMode="decimal" value={received} disabled={busy||!!pendingSale.current} onChange={e=>setReceived(e.target.value)} placeholder="0.00"/><div className="quick-cash">{Array.from(new Set([total/100,100,500,1000].filter(n=>n>=total/100))).map(n=><Button variant="outline" disabled={busy||!!pendingSale.current} key={n} onClick={()=>setReceived(String(n))}>{n===total/100?'พอดี':n}</Button>)}</div><div className="cart-total"><span>เงินทอน</span><strong>{money(Math.max(0,Math.round(Number(received||0)*100)-total))}</strong></div></>:<p>ตรวจสอบเงินเข้าในบัญชีของร้านก่อนกดยืนยัน</p>}{error&&<p role="alert" className="dialog-error">{error}</p>}<Button disabled={busy||(method==='cash'&&(!/^\d+(\.\d{1,2})?$/.test(received)||Number(received)*100<total))} onClick={pay}>{busy?'กำลังบันทึก…':pendingSale.current?'ตรวจสอบและบันทึกบิลเดิมอีกครั้ง':'ยืนยันว่าจ่ายแล้ว'}</Button>{!!pendingSale.current&&!busy&&<p className="small-muted">อย่าเริ่มบิลใหม่จนตรวจสอบบิลนี้สำเร็จ เพื่อป้องกันการคิดเงินซ้ำ</p>}</DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={v=>!busy&&!v&&setEditing(null)}><DialogContent><DialogHeader><DialogTitle>แก้ไขเมนู</DialogTitle><DialogDescription>กำหนดชื่อ ราคา และสถานะการขาย</DialogDescription></DialogHeader>{editing&&<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);act(async()=>{await api({action:'product',product:{...editing,name:form.get('name'),price:satang(String(form.get('price'))),category:form.get('category'),active:form.get('active')==='on'?1:0}});setEditing(null);await reload();});}}><Label htmlFor="product-name">ชื่อเมนู</Label><Input id="product-name" name="name" defaultValue={editing.name} required maxLength={100}/><Label htmlFor="product-price">ราคา (บาท)</Label><Input id="product-price" name="price" defaultValue={editing.price/100} inputMode="decimal" required/><Label htmlFor="product-category">หมวดหมู่</Label><Input id="product-category" name="category" defaultValue={editing.category} required maxLength={30}/><Label className="checkbox-label"><input name="active" type="checkbox" defaultChecked={!!editing.active}/>เปิดขาย</Label>{error&&<p className="dialog-error" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกเมนู'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!busy&&!v&&setDetail(null)}><DialogContent><DialogHeader><DialogTitle>บิล #{detail&&shortId(detail.id)}</DialogTitle><DialogDescription>{detail&&new Date(detail.created).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})} · {detail?.method==='cash'?'เงินสด':'เงินโอน'}</DialogDescription></DialogHeader>{detail&&<><div className="receipt-lines">{detail.items.map((l,i)=><div key={i}><span>{l.name} × {l.qty}<small>{l.note}</small></span><b>{money(l.price*l.qty)}</b></div>)}</div><div className="cart-total"><span>ยอดรวม</span><strong>{money(detail.total)}</strong></div>{detail.method==='cash'&&<p>รับมา {money(detail.received)} · ทอน {money(detail.received-detail.total)}</p>}{detail.cancelled?<p className="dialog-error">ยกเลิก: {detail.reason}</p>:<><Label htmlFor="cancel-reason">เหตุผลยกเลิกบิล (หากต้องการยกเลิก)</Label><Input id="cancel-reason" value={reason} maxLength={200} onChange={e=>setReason(e.target.value)}/>{error&&<p className="dialog-error" role="alert">{error}</p>}<Button variant="destructive" disabled={!reason.trim()||busy} onClick={()=>act(async()=>{await api({action:'cancel',id:detail.id,reason});setDetail(null);await reload();setMessage('ยกเลิกบิลแล้ว ยอดขายปรับให้เรียบร้อย');})}>ยืนยันยกเลิกบิลนี้</Button></>}</>}</DialogContent></Dialog>
 </div>;
}



