'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Account={id:string;username:string;role:string;active:number};
export default function StaffAccounts(){
 const [users,setUsers]=useState<Account[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[target,setTarget]=useState<Account|null>(null);
 async function load(){const r=await fetch('/api/users');if(!r.ok)throw new Error('โหลดบัญชีไม่ได้');const d=await r.json() as {users:Account[]};setUsers(d.users);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function save(body:unknown){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'บันทึกไม่ได้');setOpen(false);setTarget(null);await load();}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่ได้');}finally{setBusy(false);}}
 return <section className="report-section"><div className="section-heading"><h3>บัญชีผู้ใช้งาน</h3><Button onClick={()=>{setTarget(null);setError('');setOpen(true);}}>เพิ่มพนักงาน</Button></div>{error&&!open&&<p role="alert" className="dialog-error">{error}</p>}{users.map(u=><div className="account-row" key={u.id}><div><strong>{u.username}</strong><p className="small-muted">{u.role==='admin'?'แอดมิน':'พนักงาน'} · {u.active?'ใช้งานอยู่':'ปิดบัญชีแล้ว'}</p></div><Button variant="outline" disabled={busy} onClick={()=>{setTarget(u);setError('');setOpen(true);}}>จัดการ</Button></div>)}<Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent><DialogHeader><DialogTitle>{target?`บัญชี ${target.username}`:'สร้างบัญชีพนักงาน'}</DialogTitle><DialogDescription>{target?'เปลี่ยนรหัสผ่านจะออกจากระบบทุกเครื่องของบัญชีนี้':'พนักงานบันทึกการขายและยกเลิกบิลได้'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save(target?{action:'password',id:target.id,password:f.get('password')}:{action:'create',username:f.get('username'),password:f.get('password')});}}>{!target&&<><Label htmlFor="new-user">ชื่อผู้ใช้</Label><Input id="new-user" name="username" autoComplete="off" autoCapitalize="none" pattern="[A-Za-z0-9_-]{2,40}" required/></>}<Label htmlFor="new-password">{target?'รหัสผ่านใหม่':'รหัสผ่าน'}</Label><Input id="new-password" name="password" type="password" autoComplete="new-password" minLength={4} maxLength={128} required/>{error&&<p role="alert" className="dialog-error">{error}</p>}<Button type="submit" disabled={busy}>บันทึก</Button></form>{target?.role==='staff'&&!!target.active&&<Button variant="destructive" disabled={busy} onClick={()=>save({action:'disable',id:target.id})}>ปิดบัญชี {target.username} และออกจากระบบทุกเครื่อง</Button>}</DialogContent></Dialog></section>;
}
